# Generated by Django 5.2.1 on 2025-05-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asn_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_permissions',
        ),
    ]
