# Generated by Django 5.2.1 on 2025-05-18 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_shop', '0005_car_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asn_shop.manufacturer'),
            preserve_default=False,
        ),
    ]
