# Generated by Django 5.2.1 on 2025-05-18 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asn_shop', '0006_car_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='founded_year',
        ),
    ]
